# From https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/dotNET-Core.gitlab-ci.yml
image: mcr.microsoft.com/dotnet/sdk:6.0.300

stages:
  - release
  
release:
  stage: release
  artifacts:
    name: "${CI_PROJECT_TITLE}_${CI_JOB_ID}"
    expire_in: 1 day
    paths:
      - "publish/$CI_PROJECT_TITLE"
  script:
    - 'dotnet publish --no-restore -c Release --runtime win-x64 --no-self-contained --version-suffix "$CI_PIPELINE_ID" -o "publish/$CI_PROJECT_TITLE"'