version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
    volumes:
      - ./rabbitmq:/etc/rabbitmq
    
volumes:
  rabbitmq:
    